frr version 10.5
frr defaults traditional
hostname ISP1
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.255.1.1/32
!
interface eth1
 ip address 10.0.10.2/30
!
interface eth2
 ip address 10.0.20.1/30
!
interface eth3
 ip address 10.0.30.2/30
!
router bgp 65100
 bgp router-id 10.255.1.1
 no bgp ebgp-requires-policy
 neighbor 10.0.10.1 remote-as 65001
 neighbor 10.0.10.1 description CompanyA
 neighbor 10.0.20.2 remote-as 65200
 neighbor 10.0.20.2 description ISP2
 neighbor 10.0.30.1 remote-as 65002
 neighbor 10.0.30.1 description CompanyB
 !
 address-family ipv4 unicast
  neighbor 10.0.10.1 activate
  neighbor 10.0.10.1 soft-reconfiguration inbound
  neighbor 10.0.10.1 send-community all
  neighbor 10.0.20.2 activate
  neighbor 10.0.20.2 soft-reconfiguration inbound
  neighbor 10.0.20.2 send-community all
  neighbor 10.0.30.1 activate
  neighbor 10.0.30.1 soft-reconfiguration inbound
  neighbor 10.0.30.1 send-community all
 exit-address-family
!
line vty
!
